
spring:
  cloud:
    stream:
      bindings:
        pos-input-channel:
          destination: avro-pos-topic
      kafka:
        streams:
          binder:
            brokers:  localhost:9092
            configuration:
              schema.registry.url: http://localhost:8085
              processing.guarantee: exactly_once
              default:
                key: org.apache.kafka.common.serialization.Serdes$StringSerde
              value:
                serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde

