/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.avroposgenerator.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class DeliveryAddress extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8783339298366514011L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DeliveryAddress\",\"namespace\":\"com.example.avroposgenerator.model\",\"fields\":[{\"name\":\"AddressLine\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"City\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"State\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"PinCode\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"ContactNumber\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DeliveryAddress> ENCODER =
      new BinaryMessageEncoder<DeliveryAddress>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DeliveryAddress> DECODER =
      new BinaryMessageDecoder<DeliveryAddress>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<DeliveryAddress> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<DeliveryAddress> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DeliveryAddress>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this DeliveryAddress to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a DeliveryAddress from a ByteBuffer. */
  public static DeliveryAddress fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public String AddressLine;
  @Deprecated public String City;
  @Deprecated public String State;
  @Deprecated public String PinCode;
  @Deprecated public String ContactNumber;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DeliveryAddress() {}

  /**
   * All-args constructor.
   * @param AddressLine The new value for AddressLine
   * @param City The new value for City
   * @param State The new value for State
   * @param PinCode The new value for PinCode
   * @param ContactNumber The new value for ContactNumber
   */
  public DeliveryAddress(String AddressLine, String City, String State, String PinCode, String ContactNumber) {
    this.AddressLine = AddressLine;
    this.City = City;
    this.State = State;
    this.PinCode = PinCode;
    this.ContactNumber = ContactNumber;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return AddressLine;
    case 1: return City;
    case 2: return State;
    case 3: return PinCode;
    case 4: return ContactNumber;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: AddressLine = (String)value$; break;
    case 1: City = (String)value$; break;
    case 2: State = (String)value$; break;
    case 3: PinCode = (String)value$; break;
    case 4: ContactNumber = (String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'AddressLine' field.
   * @return The value of the 'AddressLine' field.
   */
  public String getAddressLine() {
    return AddressLine;
  }

  /**
   * Sets the value of the 'AddressLine' field.
   * @param value the value to set.
   */
  public void setAddressLine(String value) {
    this.AddressLine = value;
  }

  /**
   * Gets the value of the 'City' field.
   * @return The value of the 'City' field.
   */
  public String getCity() {
    return City;
  }

  /**
   * Sets the value of the 'City' field.
   * @param value the value to set.
   */
  public void setCity(String value) {
    this.City = value;
  }

  /**
   * Gets the value of the 'State' field.
   * @return The value of the 'State' field.
   */
  public String getState() {
    return State;
  }

  /**
   * Sets the value of the 'State' field.
   * @param value the value to set.
   */
  public void setState(String value) {
    this.State = value;
  }

  /**
   * Gets the value of the 'PinCode' field.
   * @return The value of the 'PinCode' field.
   */
  public String getPinCode() {
    return PinCode;
  }

  /**
   * Sets the value of the 'PinCode' field.
   * @param value the value to set.
   */
  public void setPinCode(String value) {
    this.PinCode = value;
  }

  /**
   * Gets the value of the 'ContactNumber' field.
   * @return The value of the 'ContactNumber' field.
   */
  public String getContactNumber() {
    return ContactNumber;
  }

  /**
   * Sets the value of the 'ContactNumber' field.
   * @param value the value to set.
   */
  public void setContactNumber(String value) {
    this.ContactNumber = value;
  }

  /**
   * Creates a new DeliveryAddress RecordBuilder.
   * @return A new DeliveryAddress RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new DeliveryAddress RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DeliveryAddress RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }

  /**
   * Creates a new DeliveryAddress RecordBuilder by copying an existing DeliveryAddress instance.
   * @param other The existing instance to copy.
   * @return A new DeliveryAddress RecordBuilder
   */
  public static Builder newBuilder(DeliveryAddress other) {
    return new Builder(other);
  }

  /**
   * RecordBuilder for DeliveryAddress instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DeliveryAddress>
    implements org.apache.avro.data.RecordBuilder<DeliveryAddress> {

    private String AddressLine;
    private String City;
    private String State;
    private String PinCode;
    private String ContactNumber;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.AddressLine)) {
        this.AddressLine = data().deepCopy(fields()[0].schema(), other.AddressLine);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.City)) {
        this.City = data().deepCopy(fields()[1].schema(), other.City);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.State)) {
        this.State = data().deepCopy(fields()[2].schema(), other.State);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.PinCode)) {
        this.PinCode = data().deepCopy(fields()[3].schema(), other.PinCode);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.ContactNumber)) {
        this.ContactNumber = data().deepCopy(fields()[4].schema(), other.ContactNumber);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing DeliveryAddress instance
     * @param other The existing instance to copy.
     */
    private Builder(DeliveryAddress other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.AddressLine)) {
        this.AddressLine = data().deepCopy(fields()[0].schema(), other.AddressLine);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.City)) {
        this.City = data().deepCopy(fields()[1].schema(), other.City);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.State)) {
        this.State = data().deepCopy(fields()[2].schema(), other.State);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.PinCode)) {
        this.PinCode = data().deepCopy(fields()[3].schema(), other.PinCode);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.ContactNumber)) {
        this.ContactNumber = data().deepCopy(fields()[4].schema(), other.ContactNumber);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'AddressLine' field.
      * @return The value.
      */
    public String getAddressLine() {
      return AddressLine;
    }

    /**
      * Sets the value of the 'AddressLine' field.
      * @param value The value of 'AddressLine'.
      * @return This builder.
      */
    public Builder setAddressLine(String value) {
      validate(fields()[0], value);
      this.AddressLine = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'AddressLine' field has been set.
      * @return True if the 'AddressLine' field has been set, false otherwise.
      */
    public boolean hasAddressLine() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'AddressLine' field.
      * @return This builder.
      */
    public Builder clearAddressLine() {
      AddressLine = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'City' field.
      * @return The value.
      */
    public String getCity() {
      return City;
    }

    /**
      * Sets the value of the 'City' field.
      * @param value The value of 'City'.
      * @return This builder.
      */
    public Builder setCity(String value) {
      validate(fields()[1], value);
      this.City = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'City' field has been set.
      * @return True if the 'City' field has been set, false otherwise.
      */
    public boolean hasCity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'City' field.
      * @return This builder.
      */
    public Builder clearCity() {
      City = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'State' field.
      * @return The value.
      */
    public String getState() {
      return State;
    }

    /**
      * Sets the value of the 'State' field.
      * @param value The value of 'State'.
      * @return This builder.
      */
    public Builder setState(String value) {
      validate(fields()[2], value);
      this.State = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'State' field has been set.
      * @return True if the 'State' field has been set, false otherwise.
      */
    public boolean hasState() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'State' field.
      * @return This builder.
      */
    public Builder clearState() {
      State = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'PinCode' field.
      * @return The value.
      */
    public String getPinCode() {
      return PinCode;
    }

    /**
      * Sets the value of the 'PinCode' field.
      * @param value The value of 'PinCode'.
      * @return This builder.
      */
    public Builder setPinCode(String value) {
      validate(fields()[3], value);
      this.PinCode = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'PinCode' field has been set.
      * @return True if the 'PinCode' field has been set, false otherwise.
      */
    public boolean hasPinCode() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'PinCode' field.
      * @return This builder.
      */
    public Builder clearPinCode() {
      PinCode = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'ContactNumber' field.
      * @return The value.
      */
    public String getContactNumber() {
      return ContactNumber;
    }

    /**
      * Sets the value of the 'ContactNumber' field.
      * @param value The value of 'ContactNumber'.
      * @return This builder.
      */
    public Builder setContactNumber(String value) {
      validate(fields()[4], value);
      this.ContactNumber = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'ContactNumber' field has been set.
      * @return True if the 'ContactNumber' field has been set, false otherwise.
      */
    public boolean hasContactNumber() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'ContactNumber' field.
      * @return This builder.
      */
    public Builder clearContactNumber() {
      ContactNumber = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DeliveryAddress build() {
      try {
        DeliveryAddress record = new DeliveryAddress();
        record.AddressLine = fieldSetFlags()[0] ? this.AddressLine : (String) defaultValue(fields()[0]);
        record.City = fieldSetFlags()[1] ? this.City : (String) defaultValue(fields()[1]);
        record.State = fieldSetFlags()[2] ? this.State : (String) defaultValue(fields()[2]);
        record.PinCode = fieldSetFlags()[3] ? this.PinCode : (String) defaultValue(fields()[3]);
        record.ContactNumber = fieldSetFlags()[4] ? this.ContactNumber : (String) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DeliveryAddress>
    WRITER$ = (org.apache.avro.io.DatumWriter<DeliveryAddress>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DeliveryAddress>
    READER$ = (org.apache.avro.io.DatumReader<DeliveryAddress>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
